=== TinhHuynh/prx301_samples/src/xsd/abstractType.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://xml.tinh.com/schema/abstractType"
            xmlns="http://xml.tinh.com/schema/abstractType"
            elementFormDefault="qualified">
    <xsd:complexType name="Measurement">
        <xsd:simpleContent>
            <xsd:extension base="xsd:integer">
                <xsd:attribute name="units" type="xsd:string"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>
    <xsd:element name="Weight" type="Measurement"/>
    <xsd:element name="Name" type="xsd:string"/>

    <xsd:complexType name="Animal" abstract="true">
        <xsd:sequence>
            <xsd:element ref="Name"/>
            <xsd:element ref="Weight"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Dog">
        <xsd:complexContent>
            <xsd:extension base="Animal"/>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:complexType name="Bird">
        <xsd:complexContent>
            <xsd:extension base="Animal">
                <xsd:sequence>
                    <xsd:element name="WingSpan" type="Measurement"/>
                </xsd:sequence>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:element name="Animals">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="Animal" type="Animal" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== TinhHuynh/prx301_samples/src/xsd/abstractType.xml
<Animals xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://xml.tinh.com/schema/abstractType"
         xsi:schemaLocation="http://xml.tinh.com/schema/abstractType abstractType.xsd">
    <Animal xsi:type="Dog">
        <Name>Hun</Name>
        <Weight units="pounds">23</Weight>
    </Animal>
    <Animal xsi:type="Bird">
        <Name>Kookoo</Name>
        <Weight units="grams">16</Weight>
        <WingSpan units="cm">20</WingSpan>
    </Animal>
</Animals>
