=== TinhHuynh/prx301_samples/src/xsd/extending.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://xml.tinh.com/schema/extending"
            xmlns="http://xml.tinh.com/schema/extending"
            elementFormDefault="qualified">
    <xsd:group name="person">
        <xsd:sequence>
            <xsd:element name="FirstName" type="xsd:string"/>
            <xsd:element name="MiddleName" type="xsd:string" minOccurs="0"/>
            <xsd:element name="LastName" type="xsd:string"/>
        </xsd:sequence>
    </xsd:group>

    <xsd:attributeGroup name="attGroupPerson">
        <xsd:attribute name="Title">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="Mr."/>
                    <xsd:enumeration value="Ms."/>
                    <xsd:enumeration value="Dr."/>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="BirthYear" type="xsd:gYear"/>
    </xsd:attributeGroup>

    <xsd:complexType name="Person">
        <xsd:sequence>
            <xsd:group ref="person"/>
        </xsd:sequence>
        <xsd:attributeGroup ref="attGroupPerson"/>
    </xsd:complexType>

    <xsd:complexType name="PersonExtended">
        <xsd:complexContent>
            <xsd:extension base="Person">
                <xsd:sequence>
                    <xsd:element name="Speciality">
                        <xsd:simpleType>
                            <xsd:restriction base="xsd:string">
                                <xsd:enumeration value="Mystery"/>
                                <xsd:enumeration value="Humor"/>
                                <xsd:enumeration value="Horror"/>
                                <xsd:enumeration value="Childrens"/>
                            </xsd:restriction>
                        </xsd:simpleType>
                    </xsd:element>
                </xsd:sequence>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:element name="Book">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="Title" type="xsd:string"/>
                <xsd:element name="Author" type="PersonExtended"/>
                <xsd:element name="Illustrator" type="Person"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== TinhHuynh/prx301_samples/src/xsd/extending.xml
<Book xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns="http://xml.tinh.com/schema/extending"
      xsi:schemaLocation="http://xml.tinh.com/schema/extending extending.xsd">
    <Title>How about sword ??</Title>
    <Author Title="Mr." BirthYear="1982">
        <FirstName>Ha</FirstName>
        <MiddleName>Ka</MiddleName>
        <LastName>La</LastName>
        <Speciality>Childrens</Speciality>
    </Author>
    <Illustrator Title="Ms." BirthYear="1990">
        <FirstName>Ho</FirstName>
        <MiddleName>A</MiddleName>
        <LastName>Xas</LastName>
    </Illustrator>
</Book>
