=== TinhHuynh/prx301_samples/src/xsd/occurrenceIndicator.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://xml.tinh.com/schema/occurrenceIndicator"
            xmlns="http://xml.tinh.com/schema/occurrenceIndicator"
            elementFormDefault="qualified">
    <xsd:element name="persons">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="person" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="fullName" type="xsd:string"/>
                            <xsd:element name="childName" type="xsd:string"
                                         minOccurs="0" maxOccurs="5"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== TinhHuynh/prx301_samples/src/xsd/occurrenceIndicator.xml
<?xml version="1.0" encoding="UTF-8" ?>
<persons xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://xml.tinh.com/schema/occurrenceIndicator"
         xsi:schemaLocation="http://xml.tinh.com/schema/occurrenceIndicator occurrenceIndicator.xsd">
    <person>
        <fullName>Le thi nga</fullName>
        <childName>Khanh</childName>
        <childName>Tuan</childName>
    </person>
    <person>
        <fullName>Le thi nga</fullName>
        <childName>Khanh</childName>
    </person>
    <person>
        <fullName>Le thi nga</fullName>
        <childName>Khanh</childName>
        <childName>Khanh</childName>
        <childName>Khanh</childName>
        <childName>Khanh</childName>
        <childName>Khanh</childName>
    </person>
    <person>
        <fullName>Hung</fullName>
    </person>
</persons>
