<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE Addresses [
        <!ELEMENT Addresses (Center)*>
        <!ELEMENT Center (Name, Address, Phone)>
        <!ELEMENT Name (#PCDATA)>
        <!ELEMENT Address EMPTY>
        <!ATTLIST Address id CDATA #REQUIRED>
        <!ELEMENT Phone (#PCDATA)>
        <!ENTITY HCM "123 Innovation Building HCM">
        <!ENTITY HCM "23 Block-B HiTech Zone HCM">
        <!ENTITY HN "4 BK Building HN">
        <!ENTITY DN "234 Soft Building DN">
        ]>

<Addresses>
    <Center>
        <Name>FU HCM</Name>
        <Address id="&HCM;"/>
        <Phone>092148101232</Phone>
    </Center>
    <Center>
        <Name>FU HN</Name>
        <Address id="&HN;"/>
        <Phone>092148101232</Phone>
    </Center>
    <Center>
        <Name>FU DN</Name>
        <Address id="&DN;"/>
        <Phone>092148101232</Phone>
    </Center>
</Addresses>