=== TinhHuynh/prx301_samples/src/entityParameter.dtd
<?xml version="1.0" encoding="UTF-8" ?>

        <!ELEMENT purchaseOrder (item+, manufacturer, purchaser, purchaseInfo)>
        <!ATTLIST purchaseOrder %common.attributes;>

        <!ENTITY % common.attributes
                'id         ID      #IMPLIED
                account    CDATA   #REQUIRED'
                >

        <!ELEMENT item (price, quantity)>
        <!ATTLIST item %common.attributes;>
        <!ELEMENT price (#PCDATA)>
        <!ELEMENT quantity (#PCDATA)>

        <!ELEMENT manufacturer (#PCDATA)>
        <!ATTLIST manufacturer %common.attributes;>

        <!ELEMENT purchaser (#PCDATA)>
        <!ATTLIST purchaser %common.attributes;>

        <!ELEMENT purchaseInfo (creditCard| check | cash)>
        <!ELEMENT creditCard (#PCDATA)>
        <!ELEMENT check EMPTY>
        <!ELEMENT cash ANY>

=== TinhHuynh/prx301_samples/src/entityParameter.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE purchaseOrder SYSTEM "entityParameter.dtd">
<purchaseOrder id="D001" account="Tinh">
    <item account="Tinh" id="I001">
        <price>21</price>
        <quantity>2</quantity>
    </item>
    <manufacturer account="Tinh" id="M0012">Man Co</manufacturer>
    <purchaser account="Khoa" id="P003">Ltd.</purchaser>
    <purchaseInfo>
        <cash>5999</cash>
    </purchaseInfo>
</purchaseOrder>
