<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE purchaseOrder [
        <!ELEMENT purchaseOrder (item+)>
        <!ENTITY % item
                '<!ELEMENT item (price, quantity)>'
        >
        %item;
        <!ELEMENT price (#PCDATA)>
        <!ELEMENT quantity (#PCDATA)>
        ]>
<purchaseOrder>
    <item>
        <price>21</price>
        <quantity>3</quantity>
    </item>
    <item>
        <price>45</price>
        <quantity>35</quantity>
    </item>
</purchaseOrder>