<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE purchaseOrder [
        <!ENTITY % common.attributes
                'id         ID      #IMPLIED
                account    CDATA   #REQUIRED'
                >
        <!ELEMENT purchaseOrder (item+, manufacturer, purchaser, purchaseInfo)>
        <!ATTLIST purchaseOrder %common.attributes;>
        <!ELEMENT item (price, quantity)>
        <!ATTLIST item %common.attributes;>
        <!ELEMENT price (#PCDATA)>
        <!ELEMENT quantity (#PCDATA)>

        <!ELEMENT manufacturer (#PCDATA)>
        <!ATTLIST manufacturer %common.attributes;>

        <!ELEMENT purchaser (#PCDATA)>
        <!ATTLIST purchaser %common.attributes;>

        <!ELEMENT purchaseInfo (creditCard| check | cash)>
        <!ELEMENT creditCard (#PCDATA)>
        <!ELEMENT check EMPTY>
        <!ELEMENT cash ANY>
        ]>

<purchaseOrder account="wdasd">
    <item account="asasd">
        <price>22</price>
        <quantity>12</quantity>
    </item>
    <manufacturer account="xxx">Academic</manufacturer>
    <purchaser account="asada">Ltd</purchaser>
    <purchaseInfo>
        <cash>21</cash>
    </purchaseInfo>
</purchaseOrder>