=== TinhHuynh/prx301_samples/src/letter.dtd
<?xml version="1.0" encoding="utf-8" ?>

        <!ELEMENT letter (contact+, salutation, paragraph+, closing, signature)>
        <!ELEMENT contact (name, address, city, phone, flag)>
        <!ATTLIST contact type CDATA #REQUIRED>

        <!ELEMENT name (#PCDATA)>
        <!ELEMENT address (#PCDATA)>
        <!ELEMENT city (#PCDATA)>
        <!ELEMENT phone (#PCDATA)>
        <!ELEMENT flag EMPTY>
        <!ATTLIST flag gender CDATA #REQUIRED
                desp CDATA #IMPLIED>

        <!ELEMENT salutation (#PCDATA)>
        <!ELEMENT paragraph (#PCDATA)>
        <!ELEMENT closing (#PCDATA)>
        <!ELEMENT signature (#PCDATA)>

=== TinhHuynh/prx301_samples/src/dtd/letter.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE letter SYSTEM "/home/TinhHSE62713/Projects/DtdXml2/src/dtd/letter.dtd">
<letter>
    <contact type="from">
        <name>Tinh</name>
        <address>To Ky</address>
        <city>HCMC</city>
        <phone>112</phone>
        <flag gender="M" desp="a"/>
    </contact>
    <contact type="to">
        <name>Khoa</name>
        <address>Unknown</address>
        <city>Vung Tau</city>
        <phone>122</phone>
        <flag gender="a" desp="a"/>
    </contact>
    <salutation>Dear Khoa</salutation>
    <paragraph>I want to be your friend. Do you accept me ?</paragraph>
    <closing>Thank you</closing>
    <signature>Tinh</signature>
</letter>

=== TinhHuynh/prx301_samples/out/production/DtdXml2/letter.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE letter SYSTEM "letter.dtd">
<letter>
    <contact type="from">
        <name>Tinh</name>
        <address>To Ky</address>
        <city>HCMC</city>
        <phone>112</phone>
        <flag gender="f"/>
    </contact>
    <contact type="to">
        <name>Khoa</name>
        <address>Unknown</address>
        <city>Vung Tau</city>
        <phone>122</phone>
        <flag gender="F"/>
    </contact>
    <salutation>Dear Khoa</salutation>
    <paragraph>I want to be your friend. Do you accept me ?</paragraph>
    <closing>Thank you</closing>
    <signature>Tinh</signature>
</letter>
